FROM ubuntu:latest
RUN apt-get update -y && apt-get upgrade -y
RUN apt-get install libssl-dev openssl -y
RUN mkdir -p /credentials
#COPY tracker-184b3-firebase.json /credentials/tracker-184b3-firebase.json


